apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    # Does this have to access the users in the machine?
    # When doing this from my own machine, I used the path "/c/Users/"
    path: "/home/ec2-user/"
