apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-deployment-4reps
  name: nginx-deployment-4reps
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-deployment-4reps
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-deployment-4reps
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}

  # File created with the following command:
  # `kubectl create deployment --image=nginx nginx --dry-run=client -o yaml > nginx-deployment.yaml`

