apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
  - targetPort: 80
    port: 80
    nodePort: 30008
  # The `selector` links the service to the pod, via that pods metadata.labels - (see `pod-definition.yml` metadata to confirm)
  selector:
    app: myapp
    type: front-end

## A service is an object INSIDE the node your pod is stationed in.
  # The `targetPort` is the port of the pod.
    # If not provided, it will be assumed it is the same as the port.

  # The `port` is the port of the Service.

  # The `nodePort` is the port used to connect from external sources.
    # If not provided, a free port (in the range of 30000-32767) will be provided.

