apiVersion: v1
kind: ReplicationController
metadata: # metadata for the RC
  name: myapp-rc
  labels:
    app: myapp
    type: front-end
spec: # specs for the RC
  template:
    metadata: # metadata for the pod
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec: # specs for the pod
      containers: #List/Array
      - name: nginx-container
        image: nginx
  replicas: 3
