apiVersion: v1
kind: Secret
metadata:
  name: app-secret
    # mysel=bXlzxWw= <-- encrypted via `echo -n 'mysql' | base64` command; the below is the same
    # root=cm9cdA==
    # paswrd=cGfzd3Jk
data:
  DB_Host: mysql
  DB_User: root
  DB_Password: paswrd
